[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

; This automagically downloads the correct drivers for the Plus 2
lib_deps = 
    m5stack/M5StickCPlus2